{
  config,
  lib,
  ...
}: let
  cfg = config.dotfiles.customSshd;

  sshdConfig = builtins.toFile "custom-sshd-config" ''
    Port ${toString cfg.port}
    HostKey /etc/ssh/ssh_host_ed25519_key
    HostKey /etc/ssh/ssh_host_rsa_key
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    UsePAM yes
    AllowUsers ${config.system.primaryUser}
    AuthorizedKeysFile .ssh/authorized_keys
    Subsystem sftp /usr/libexec/sftp-server
  '';
in {
  options.dotfiles.customSshd = {
    enable = lib.mkEnableOption ''
      an independent sshd instance on a non-standard port, using the
      Apple-signed /usr/sbin/sshd binary. Unlike services.openssh (macOS
      Remote Login), this launchd daemon is not controlled by the Remote
      Login preference, so MDM policies that toggle Remote Login off do not
      affect it. Key-only auth, primary user only
    '';

    port = lib.mkOption {
      type = lib.types.port;
      default = 2222;
      description = "Port for the custom sshd instance.";
    };
  };

  config = lib.mkIf cfg.enable {
    system.requiresPrimaryUser = ["dotfiles.customSshd.enable"];

    launchd.daemons.dotfiles-custom-sshd.serviceConfig = {
      # -D keeps sshd in the foreground so launchd supervises it; -e sends
      # logs to stderr. The Apple-signed binary passes the application
      # firewall's "automatically allow built-in software" rule, which a
      # nixpkgs sshd would not. Host keys are generated by ssh-keygen -A
      # below if the machine has never enabled Remote Login.
      ProgramArguments = [
        "/bin/sh"
        "-c"
        "/usr/bin/ssh-keygen -A && exec /usr/sbin/sshd -D -e -f ${sshdConfig}"
      ];
      KeepAlive = true;
      RunAtLoad = true;
      StandardErrorPath = "/var/log/dotfiles-custom-sshd.log";
    };
  };
}
