{ pkgs, lib, ... }:

let

  mkINI = lib.generators.toINI {
    mkKeyValue = key: value:
      let
        v = if lib.isBool value then
            (if value then "True" else "False")
          else
            toString value;
      in "${key} = ${v}";
  };

  mycliConfig = {
      general = {
        smart_completion = true;
        multi_line = true;
        destructive_warning = true;
        table_format = "ascii";
        key_bindings = "vi";
        wider_completion_menu = true;
        less_chatty = true;
        keyword_casing = "auto";
        enable_pager = true;
      };
    };
in {

  home.packages = with pkgs; [
    mycli
  ];

  home.file.".myclirc".text = ''
    # Generated by home-manager from nixpkgs.mycli in ~/dotfiles
    # For a list of options see: https://www.mycli.net/config

  '' + mkINI mycliConfig;
}
