# Native aarch64 build for trainwreck. This avoids QEMU on the x86_64 jobs.
image: nixos/unstable
arch: aarch64
packages:
  - nixos.cachix
sources:
  - https://git.sr.ht/~averagechris/dotfiles
secrets:
  - 731f7e55-4497-4228-8fa4-1657da7d3625
tasks:
  - setup: |
      source ~/dotfiles/scripts/ci-setup.sh

  - trainwreck-build: |
      cd ~/dotfiles
      scripts/ci-check-tiers.sh trainwreck-build
