#!/usr/bin/env sh

yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_opacity               off

yabai -m config window_border                off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6


# allow windows from these applications to float
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Messages$" manage=off

# float emacs popup windwos used for autocompletion etc
yabai -m rule --add app='^Emacs$' title!="^Emacs@$USER" manage=off

# float iterm window that emulate guake (floats from bottom)
yabai -m rule --add app='^iTerm2$' title="^Hotkey Window$" manage=off

echo "$(date "+%Y-%m-%d %H:%M:%s") - yabai configuration loaded..."
