{runtimeNote}: {
  build = ''
    ---
    description: Build agent - full development and code change workflows
    mode: all
    temperature: 0.0
    steps: 120
    permission:
      read: "allow"
      edit: "allow"
      glob: "allow"
      grep: "allow"
      list: "allow"
      webfetch: "allow"
      bash:
        "*": "ask"
        "alejandra": "allow"
        "alejandra *": "allow"
        "awk*": "ask"
        "cat": "allow"
        "cat *": "allow"
        "echo": "allow"
        "echo *": "allow"
        "fd": "allow"
        "fd *": "allow"
        "find": "allow"
        "find *": "allow"
        "grep": "allow"
        "grep *": "allow"
        "head": "allow"
        "head *": "allow"
        "ls": "allow"
        "ls *": "allow"
        "rg": "allow"
        "rg *": "allow"
        "sed": "allow"
        "sed *": "allow"
        "sort": "allow"
        "sort *": "allow"
        "tail": "allow"
        "tail *": "allow"
        "wc": "allow"
        "wc *": "allow"
        "which": "allow"
        "which *": "allow"
        "cargo": "allow"
        "cargo *": "allow"
        "gh *": "allow"
        "gh auth*": "ask"
        "gh org*": "ask"
        "gh issue*": "ask"
        "gh repo*": "ask"
        "linear *": "allow"
        "jj *": "allow"
        "jj abandon*": "ask"
        "jj bookmark delete*": "ask"
        "jj bookmark move*": "ask"
        "jj bookmark set*": "ask"
        "jj commit*": "ask"
        "just": "allow"
        "just *": "allow"
        "kubectl api-resources": "allow"
        "kubectl api-resources *": "allow"
        "kubectl api-versions": "allow"
        "kubectl api-versions *": "allow"
        "kubectl auth can-i": "allow"
        "kubectl auth can-i *": "allow"
        "kubectl cluster-info": "allow"
        "kubectl cluster-info *": "allow"
        "kubectl config current-context": "allow"
        "kubectl config get-contexts": "allow"
        "kubectl config get-contexts *": "allow"
        "kubectl describe": "allow"
        "kubectl describe *": "allow"
        "kubectl describe *secret*": "ask"
        "kubectl events": "allow"
        "kubectl events *": "allow"
        "kubectl explain": "allow"
        "kubectl explain *": "allow"
        "kubectl get": "allow"
        "kubectl get *": "allow"
        "kubectl get *secret*": "ask"
        "kubectl logs": "allow"
        "kubectl logs *": "allow"
        "kubectl top": "allow"
        "kubectl top *": "allow"
        "kubectl version": "allow"
        "kubectl version *": "allow"
        "make": "allow"
        "make *": "allow"
        "mypy": "allow"
        "mypy *": "allow"
        "nix": "allow"
        "nix *": "allow"
        "nix-instantiate": "allow"
        "nix-instantiate *": "allow"
        "nix-store": "allow"
        "nix-store *": "allow"
        "nixos-rebuild build": "allow"
        "nixos-rebuild build *": "allow"
        "darwin-rebuild build": "allow"
        "darwin-rebuild build *": "allow"
        "pre-commit": "allow"
        "pre-commit *": "allow"
        "pup": "allow"
        "pup *": "allow"
        "pytest": "allow"
        "pytest *": "allow"
        "rodney": "allow"
        "rodney *": "allow"
        "ruff": "allow"
        "ruff *": "allow"
        "sentry": "allow"
        "sentry *": "allow"
        "statix": "allow"
        "statix *": "allow"
        "surecraft": "allow"
        "surecraft *": "allow"
      skill:
        "*": "allow"
      task:
        "*": "deny"
        "build": "allow"
        "explore": "allow"
    ---

    You are the Build primary agent. Use this agent for full development and code change workflows.
    ALWAYS USE `jj` over `git` for version control actions.
    ${runtimeNote}
  '';

  plan = ''
    ---
    description: Plan agent - analysis and planning (read-only)
    mode: primary
    temperature: 0.0
    steps: 50
    permission:
      read: "allow"
      edit: "deny"
      glob: "allow"
      grep: "allow"
      list: "allow"
      webfetch: "allow"
      bash:
        "*": "deny"
        "cat": "allow"
        "cat *": "allow"
        "echo": "allow"
        "echo *": "allow"
        "fd": "allow"
        "fd *": "allow"
        "find": "allow"
        "find *": "allow"
        "grep": "allow"
        "grep *": "allow"
        "head": "allow"
        "head *": "allow"
        "ls": "allow"
        "ls *": "allow"
        "rg": "allow"
        "rg *": "allow"
        "sort": "allow"
        "sort *": "allow"
        "tail": "allow"
        "tail *": "allow"
        "wc": "allow"
        "wc *": "allow"
        "which": "allow"
        "which *": "allow"
        "cargo": "allow"
        "cargo *": "allow"
        "jj bookmark list": "allow"
        "jj bookmark list *": "allow"
        "jj config": "allow"
        "jj config *": "allow"
        "jj diff": "allow"
        "jj diff *": "allow"
        "jj files": "allow"
        "jj files *": "allow"
        "jj log": "allow"
        "jj log *": "allow"
        "jj op log": "allow"
        "jj op log *": "allow"
        "jj resolve --list": "allow"
        "jj resolve --list *": "allow"
        "jj show": "allow"
        "jj show *": "allow"
        "jj status": "allow"
        "jj status *": "allow"
        "nix eval": "allow"
        "nix eval *": "allow"
        "nix flake show": "allow"
        "nix flake show *": "allow"
      skill:
        "*": "allow"
      task:
        "*": "deny"
        "build": "allow"
        "explore": "allow"
    ---

    You are the Plan primary agent. Focus on analysis, planning, and proposing changes without making edits.

    - ALWAYS USE `jj` over `git` for version control actions.
    - Structure outputs to match the task — at minimum: what you found, what you propose, and what the risks are.
    - ${runtimeNote}
  '';
}
