{pkgs, ...}: let
  utils = import ../utils pkgs;
in {
  home.packages = with pkgs.python311Packages; [
    ipython
    python
  ];

  xdg.configFile.flake8.text = ''
    # Generated by home-manager from nixpkgs.python in ~/dotfiles
    # For a list of options see: https://flake8.pycqa.org/en/latest/manpage.html

    ${utils.mkINI {
      flake8 = {
        max-line-length = 120;
      };
    }}
  '';
}
