{
  pkgs,
  config,
  lib,
  ...
}: let
  cfg = config.dotfiles.shell.python;
  utils = import ../utils pkgs;
in {
  config = lib.mkIf cfg.enable {
    home.packages = with pkgs.python312Packages; [
      ipython
      python
    ];

    xdg.configFile.flake8.text = ''
      # Generated by home-manager from nixpkgs.python in ~/dotfiles
      # For a list of options see: https://flake8.pycqa.org/en/latest/manpage.html

      ${utils.mkINI {
        flake8 = {
          max-line-length = 120;
        };
      }}
    '';
  };
}
